In [21]:
import numpy as np
import matplotlib.pylab as plt
import pandas as pd

In [22]:
Consump=pd.read_csv('/home/bleon/Documents/DS4A/DS4A_Project/Processed_Data/ResidencesUnited.csv')
Consump.dtypes

Unnamed: 0                          int64
Time Bucket (America/New_York)     object
JFP_1 (kWhs)                      float64
JFP_2 (kWhs)                      float64
room outlets (kWhs)               float64
Heater  (kWhs)                    float64
Hall Light (kWhs)                 float64
Oven (kWhs)                       float64
Family Light (kWhs)               float64
Fridge (kWhs)                     float64
Washer/Dryer (kWhs)               float64
Fam Outlets (kWhs)                float64
dtype: object

In [23]:
pd.DataFrame(Consump.describe()).iloc[1]

Unnamed: 0             4380.000000
JFP_1 (kWhs)              0.193790
JFP_2 (kWhs)              0.202328
room outlets (kWhs)       0.028621
Heater  (kWhs)            0.024608
Hall Light (kWhs)         0.000378
Oven (kWhs)               0.048639
Family Light (kWhs)       0.028496
Fridge (kWhs)             0.106760
Washer/Dryer (kWhs)       0.032913
Fam Outlets (kWhs)        0.069671
Name: mean, dtype: float64

In [24]:
Consump['datetime']=pd.to_datetime(Consump['Time Bucket (America/New_York)'])
Consump.drop(columns=['Time Bucket (America/New_York)','Unnamed: 0'],inplace=True)
Consump['Year']=Consump['datetime'].dt.year
Consump['Month']=Consump['datetime'].dt.month
Consump['Day']=Consump['datetime'].dt.day
print(Consump.describe())

       JFP_1 (kWhs)  JFP_2 (kWhs)  room outlets (kWhs)  Heater  (kWhs)  \
count   8761.000000   8761.000000          8761.000000     8761.000000
mean       0.193790      0.202328             0.028621        0.024608
std        0.214055      0.175153             0.049137        0.101495
min        0.000000      0.000000             0.000000        0.000000
25%        0.077000      0.116000             0.000000        0.000000
50%        0.148000      0.167000             0.007000        0.000000
75%        0.239000      0.221000             0.049000        0.000000
max        2.372000      1.906000             0.756000        1.378000

       Hall Light (kWhs)  Oven (kWhs)  Family Light (kWhs)  Fridge (kWhs)  \
count        8761.000000  8761.000000          8761.000000    8761.000000
mean            0.000378     0.048639             0.028496       0.106760
std             0.003187     0.174968             0.023084       0.049557
min             0.000000     0.000000             0.000000       0.000000
25%             0.000000     0.000000             0.000000       0.079000
50%             0.000000     0.000000             0.036000       0.112000
75%             0.000000     0.000000             0.045000       0.137000
max             0.058000     3.128000             0.125000       0.401000

       Washer/Dryer (kWhs)  Fam Outlets (kWhs)         Year        Month  \
count          8761.000000         8761.000000  8761.000000  8761.000000
mean              0.032913            0.069671  2020.202260     6.526538
std               0.252241            0.049952     0.401708     3.448183
min               0.000000            0.000000  2020.000000     1.000000
25%               0.000000            0.042000  2020.000000     4.000000
50%               0.000000            0.047000  2020.000000     7.000000
75%               0.000000            0.088000  2020.000000    10.000000
max               3.970000            0.414000  2021.000000    12.000000

               Day
count  8761.000000
mean     15.718982
std       8.797637
min       1.000000
25%       8.000000
50%      16.000000
75%      23.000000
max      31.000000

In [27]:

Consump=Consump.sort_values(by=["Month","Day"]).reset_index(drop=True)
Consump["Year"]=2020
Consump

,JFP_1 (kWhs),JFP_2 (kWhs),room outlets (kWhs),Heater (kWhs),Hall Light (kWhs),Oven (kWhs),Family Light (kWhs),Fridge (kWhs),Washer/Dryer (kWhs),Fam Outlets (kWhs),datetime,Year,Month,Day
0,0.289,0.208,0.000,0.0,0.005,0.000,0.047,0.151,0.0,0.198,2021-01-01 00:00:00,2020,1,1
1,0.269,0.206,0.000,0.0,0.002,0.000,0.047,0.145,0.0,0.198,2021-01-01 01:00:00,2020,1,1
2,0.160,0.196,0.000,0.0,0.003,0.000,0.046,0.142,0.0,0.067,2021-01-01 02:00:00,2020,1,1
3,0.147,0.184,0.000,0.0,0.000,0.000,0.042,0.136,0.0,0.046,2021-01-01 03:00:00,2020,1,1
4,0.140,0.179,0.000,0.0,0.000,0.000,0.042,0.131,0.0,0.039,2021-01-01 04:00:00,2020,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8756,0.686,0.469,0.119,0.0,0.000,0.571,0.053,0.136,0.0,0.215,2020-12-31 19:00:00,2020,12,31
8757,0.436,0.258,0.027,0.0,0.001,0.144,0.052,0.128,0.0,0.200,2020-12-31 20:00:00,2020,12,31
8758,0.525,0.383,0.027,0.0,0.000,0.380,0.048,0.140,0.0,0.198,2020-12-31 21:00:00,2020,12,31
8759,0.272,0.120,0.000,0.0,0.000,0.000,0.050,0.086,0.0,0.199,2020-12-31 22:00:00,2020,12,31
8760,0.274,0.090,0.000,0.0,0.000,0.002,0.045,0.064,0.0,0.199,2020-12-31 23:00:00,2020,12,31

In [31]:
Consump_month=Consump.drop(columns=["datetime","Day"]).groupby(["Month","Year"]).sum()
Consump_month.to_csv('/home/bleon/Documents/DS4A/DS4A_Project/Processed_Data/Consumption_month.csv')
Consump.to_csv('/home/bleon/Documents/DS4A/DS4A_Project/Processed_Data/Consumption_hour.csv')